version: '3.4'

services:
  catalogdb: 
    image: mongo

  catalog2.api:
    image: ${DOCKER_REGISTRY-}catalog2api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog2.API/Dockerfile

volumes: 
  mongo_data:    